### PR TITLE
Added composer files to .gitignore

### PR DESCRIPTION
**Pull request by trickeydan**
These files do not need to be included as composer will install them.
It is bad practice to include them as it duplicates code and could potentially let people run outdated or insecure libraries!

### CODE REVIEW

**Comment by malle-pietje** [comment]
Thanks, I know and am fully aware of this being bad practice. I'll reconsider adding this to the ignore file, again.

**Comment by malle-pietje** [comment]
On another note, I don't agree that leaving them out will prevent "people run outdated or insecure libraries". Once they have installed composer without having a clue what it is and how powerful it is, they can still easily shoot themselves in the foot.

**Comment by trickeydan** [comment]
By including a copy of the libraries, it is inherently a security risk as there may be a flaw in those libraries. As the user isn't using composer, the libraries will not be updated.

**Comment by malle-pietje** [comment]
If this is regarding moving responsibilities to the end-user, I can understand your PR. I have however decided to approach this in a different manner.

**Pull request closed without merging**
