### PR TITLE
Composer changes

### PR DESCRIPTION
**Pull request by captn3m0**
- Removed `vendor` directory from the repo
- Added composer.phar binary instead to install the latest dependencies as per composer.lock
- Unpinned `kint` dependency

Possible suggestion: you might wanna move `kint` to require-dev, but I haven't checked the codebase for usage so didn't change it yet

### CODE REVIEW

**Comment by malle-pietje** [comment]
@captn3m0 Thanks for the input. I have been considering this approach but the downside is one more required step for the user when installing/updating the tool. The upside is reduced clutter in the git history and the commits.

I'll have another good think about this; I do like the idea of including the composer.phar file.

Regarding the Kint version; I decided to freeze the KInt version and avoid any negative impact from new releases.

**Comment by malle-pietje** [comment]
After a second thought I'm not so sure I should include a .phar file. I will get back asap with more feedback.

**Comment by captn3m0** [comment]
I decided to add the `composer.phar` file to keep the installation easy enough. However, it is a 2MB binary, so I'm not sure if keeping it is the right approach. Laravel used to include it earlier, but stopped in favor of letting the user install composer themselves.

Also, have you considered upgrading the unifi client package to a curl wrapper instead? I might do it, if you think it is worthwhile.

**Comment by malle-pietje** [comment]
Yes, the size is a concern, but even more the fact that it's a binary, limiting validation of that bit of code by the users. Remember, most users of the API browser aren't necessarily skilled PHP developers, so ease of installation and elimination/reduction of dependencies is key.

**Comment by malle-pietje** [comment]
I'll close this for now since I have decided to pre-load the vendor directory. Reasons are I want the tool to have as few requirements as possible and also because the included package is under our own control and tightly coupled to the API browser tool itself (changes in the client class package could be just as relevant to the users as most of the changes to the API browser tool).

Feel free to open the PR again if you feel the need to do so.

**Comment by captn3m0** [comment]
Thanks for the update :+1:

**Pull request closed without merging**
