### PR TITLE
No-fuss docker quick-start

### PR DESCRIPTION
**Pull request by dagelf**

### CODE REVIEW

**Comment by malle-pietje** [comment]
Thanks, makes more sense here😉 Will try to review this over the weekend.

**Comment by malle-pietje** [comment]
OK, I had a look at this but I am unable to get a Docker container working with these commands. Can you please double-check? This is on OpenSuse with docker already installed.

**Comment by dagelf** [comment]
Thanks for trying it out... I thought that was really super fool-proof, I guess I need to make it even simpler. 

It could be one of 3 things:

1.  Try sudo in front of docker
2.  Try it without the bind mount - `docker run --rm -ti -p 8000:8000 alpine sh -c "cd /usr/src && apk update && apk add php php-session php-curl composer git && git clone --depth 1 https://github.com/Art-of-WiFi/UniFi-API-browser.git && cd UniFi-API-browser && composer install && php -S 0:8000 || sh"`
3. Port 8000 is used, try another port, or omit `-p 8000:8000`

The only snag is that the second method, you need to remember the containerid, and enter the docker container to make changes, so you can't use the editors on the host: `docker exec -ti containerid sh`, and you need to copy out the changes you'd like to keep, as it always starts with a fresh copy. You can also omit the `--rm`, which makes the container ephemeral so that when it crashes, it doesn't leave behind a long list of used containers from every time you "ran" one - they don't take much space and allow a post-mortem - but you have to remember to find them with `docker ps -a` and manually remove with `docker rm containerid `

If the first one works, then it's just the ownership of /usr/src blocking it.  The second one can run without sudo. You can also omit the `-p 8000:8000` and look up the IP address for the container `docker inspect containerid|grep 172` - and load it directly.

If it;'s a path issue, I guess it'd be better to not make the path absolute. That's an easy change, but we'd still have to add `sudo` as well as a ```pwd``` next to the `-v`, happy to do that. 

Or we can do it like everyone else and put the commands in a Dockerfile, create an image, maintain a dockerhub account, etc... but that defeats the purpose of having a  quick, universal one-liner to get everyone up and running and using this and improving Unifi, quicker...

**Comment by malle-pietje** [comment]
OK, makes sense. I've tried using your latest command and now get this output:
```bash
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
8e402f1a9c57: Pull complete 
Digest: sha256:644fcb1a676b5165371437feaa922943aaf7afcfa8bfee4472f6860aad1ef2a0
Status: Downloaded newer image for alpine:latest
sh: cd: line 1: can't cd to /usr/src: No such file or directory
```

**Comment by malle-pietje** [comment]
I think the error was caused by the `/usr/src` directory missing from the alpine dicker container, not locally. This was the exact command I used:
```bash
sudo docker run --rm -ti -p 8000:8000 alpine sh -c "cd /usr/src && apk update && apk add php php-session php-curl composer git && git clone --depth 1 https://github.com/Art-of-WiFi/UniFi-API-browser.git && cd UniFi-API-browser && composer install && php -S 0:8000 || sh"
```

**Comment by dagelf** [comment]
Oops, I thought that was a standard path in the Linux tree. You can just omit the `cd /usr/src`, or change it to any other path eg. `cd /` and let it git clone there, in a temporary container it really doesn't matter. 

The point of this is to get an easy oneliner that will run everywhere, with the same dependencies. To make it even more portable we can force a specific version of alpine.

**Comment by malle-pietje** [comment]
Doesn't really matter where it is installed in the container, as long as the instructions are clear and fool-proof. I simply don't want to get flooded with messages from people who are running into issues getting their Docker container started...

**Comment by scyto** [comment]
Did this get constructed into a docker file / hosted on docker hub?

**Comment by malle-pietje** [comment]
@scyto Not that I’m aware of. This would indeed be the preferred approach and I can simply add a pointer to Docker Hub.

The pre-reqs are pretty straightforward: PHP 7.2/7.3, Apache 2.4, cURL and git

**Comment by scyto** [comment]
cool, i will see what i can do, for now i will assume port 8000 and if we get that working then can look at changes that might impact code.

**Comment by malle-pietje** [comment]
> cool, i will see what i can do, for now i will assume port 8000 and if we get that working then can look at changes that might impact code.

Sounds like a plan!

**Comment by scyto** [comment]
@malle-pietje give this a try, i will do reame.md etc for it later, just wanted to get it quickly up and running
https://hub.docker.com/r/scyto/unifibrowser

**Comment by scyto** [comment]
I assume i can uninstall git in my dockerfile, can I do the same for compose so long as  i do it after the the `composer install` command?

**Comment by malle-pietje** [comment]
Yes, for the docker container it makes sense to remove git since it would only be used to pull a code update.

Composer isn’t required to install the API browser tool because we bundle the PHP API client class because we wanted to make the install as easy as possible with minimal requirements. Also, composer is becoming quite bulky and I have read reports about excessive memory consumption...

**Comment by scyto** [comment]
Sorry I am a little confused, can I remove the composer at the end of the RUN sequence?

**Comment by malle-pietje** [comment]
You don’t need composer at all to install the API browser, only when you want to install the PHP API client for inclusion in a project.

**Comment by scyto** [comment]
Thanks for the clarification, I will remove the composer install command tomorrow. I am PDT TZ.

**Comment by scyto** [comment]
@malle-pietje ok done, also made the readme.md a little more robust.  If you have docker would you mind testing?  Once you have verified i guess this commit can be cancelled and we can add a link to the wiki instead?

**Comment by scyto** [comment]
hmm removal of composer install line seem to have broken it.... will add back in

**Comment by scyto** [comment]
@malle-pietje issue doesn't seem to be composer install line, i get the same runtime issues with it added back in:

`PHP 7.3.10 Development Server started at Fri Oct  4 19:03:37 2019
[Fri Oct  4 19:03:43 2019] PHP Fatal error:  Uncaught Error: Call to undefined function json_decode() in /UniFi-API-browser/index.php:676
Stack trace:
#0 /UniFi-API-browser/index.php(21): get_client_version()
#1 {main}
  thrown in /UniFi-API-browser/index.php on line 676
[Fri Oct  4 19:03:43 2019] 172.17.0.1:43490 [500]: / - Uncaught Error: Call to undefined function json_decode() in /UniFi-API-browser/index.php:676
Stack trace:
#0 /UniFi-API-browser/index.php(21): get_client_version()
#1 {main}
  thrown in /UniFi-API-browser/index.php on line 676
`

**Comment by malle-pietje** [comment]
@scyto Were you using Apache as the webserver or the PHP built-in webserver?

**Comment by scyto** [comment]
I assume php - I just deconstructed the docke run command posted way above, so whatever that is doing?

**Comment by malle-pietje** [comment]
Looking at the command it appears to be using the built-in PHP web server. Why omitting composer breaks things is a mystery to me unless you didn’t modify the full command and left the `composer update` part in.

**Comment by scyto** [comment]
Nope, never called composer update.
It seems composer is instantiated as a class in the php code the error codes referenced it at line 600ish IIRC (sorry if my language is imprecise, I am not a coder).

Either way you have a no fuss docker quick start for amd64 if you want to reference the image and close this ticket!?

**Comment by malle-pietje** [comment]
My bad, I meant `composer install`. Normally not needed since composer is basically a package manager for PHP, not a module for actual code and all required packages are included when you’ve run ‘`git clone`.

**Comment by scyto** [comment]
np, i believe this is what errored when i didn't install compose OR run composer install.

```
/**
 * function which returns the version of the included API client class by
 * extracting it from the composer.lock file
 */
function get_client_version()
{
    if (is_readable('composer.lock')) {
        $composer_lock = file_get_contents('composer.lock');
        $json_decoded = json_decode($composer_lock, true);
        if (isset($json_decoded['packages'])) {
            foreach ($json_decoded['packages'] as $package) {
                if ($package['name'] === 'art-of-wifi/unifi-api-client') {
                    return substr($package['version'], 1);
                }
            }
        }
    }
    return 'unknown';
}
```

**Comment by malle-pietje** [comment]
Correct, but that shouldn't throw an error when composer isn't installed.

**Comment by scyto** [comment]
I hear you, but that was my experience, it is possible i made a systematic error like say adding the package, ran the composer install and removed the package and it errored.  But pretty sure i tried multiple variations (so unless i messed up on the changes in github...)

I will leave it in the docker for now as it does no harm and come back to it when i have time to crack the dockerfile open again.  (i want to learn multi-arch builds using gits pre/post hooks - but thats a whiles away yet).

**Comment by malle-pietje** [comment]
Understood. Will see whether I can test this sometime this week.

**Comment by scyto** [comment]
thanks, IIRC i think this might be the failing build, this is the one without any compose stuff at all (thank god one can go back and look at old builds and their docker files :-) this is only my second public image!) https://cloud.docker.com/u/scyto/repository/docker/scyto/unifibrowser/builds/4de57b19-2707-46e9-98ed-c600c5d2a7ff

**Comment by scyto** [comment]
i guess since i made https://hub.docker.com/r/scyto/unifibrowser my comments are dead, not sure that affects the pull mind you.

**Comment by malle-pietje** [comment]
@scyto I assumed that with the added link in the `README.md` file to the WiKi page this PR was no longer needed. If that assumption is incorrect, just let me know.

**Pull request closed without merging**
